import { v4 as uuidv4 } from 'uuid';

export const statusTypes = [
  { title: 'do zrobienia', key: 'status', id: uuidv4() },
  { title: 'zrobione', key: 'status', id: uuidv4() },
];

export const deviceTypes = [
  { title: 'telefon', key: 'rodzaj', id: uuidv4() },
  { title: 'laptop', key: 'rodzaj', id: uuidv4() },
  { title: 'PC', key: 'rodzaj', id: uuidv4() },
  { title: 'konsola', key: 'rodzaj', id: uuidv4() },
  { title: 'smartwatch', key: 'rodzaj', id: uuidv4() },
  { title: 'tablet', key: 'rodzaj', id: uuidv4() },
  { title: 'inne', key: 'rodzaj', id: uuidv4() },
];

export const brandTypes = [
  { title: '3D Cell', key: 'marka', id: uuidv4() },
  { title: 'Acer', key: 'marka', id: uuidv4() },
  { title: 'Alcatel', key: 'marka', id: uuidv4() },
  { title: 'Apple', key: 'marka', id: uuidv4() },
  { title: 'Asus', key: 'marka', id: uuidv4() },
  { title: 'BlackBerry', key: 'marka', id: uuidv4() },
  { title: 'Dell', key: 'marka', id: uuidv4() },
  { title: 'Blackview', key: 'marka', id: uuidv4() },
  { title: 'Denon', key: 'marka', id: uuidv4() },
  { title: 'Doogee', key: 'marka', id: uuidv4() },
  { title: 'Dream Machines', key: 'marka', id: uuidv4() },
  { title: 'Gigabyte', key: 'marka', id: uuidv4() },
  { title: 'Google', key: 'marka', id: uuidv4() },
  { title: 'Hammer', key: 'marka', id: uuidv4() },
  { title: 'Honor', key: 'marka', id: uuidv4() },
  { title: 'HP', key: 'marka', id: uuidv4() },
  { title: 'HTC', key: 'marka', id: uuidv4() },
  { title: 'Huawei', key: 'marka', id: uuidv4() },
  { title: 'Lenovo', key: 'marka', id: uuidv4() },
  { title: 'LG', key: 'marka', id: uuidv4() },
  { title: 'Microsoft', key: 'marka', id: uuidv4() },
  { title: 'Motorola', key: 'marka', id: uuidv4() },
  { title: 'Nokia', key: 'marka', id: uuidv4() },
  { title: 'OnePlus', key: 'marka', id: uuidv4() },
  { title: 'Oppo', key: 'marka', id: uuidv4() },
  { title: 'Panasonic', key: 'marka', id: uuidv4() },
  { title: 'Samsung', key: 'marka', id: uuidv4() },
  { title: 'Sony', key: 'marka', id: uuidv4() },
  { title: 'Toshiba', key: 'marka', id: uuidv4() },
  { title: 'Ulefone', key: 'marka', id: uuidv4() },
  { title: 'Williams', key: 'marka', id: uuidv4() },
  { title: 'Xiaomi', key: 'marka', id: uuidv4() },
  { title: 'Xperia', key: 'marka', id: uuidv4() },
  { title: 'ZTE', key: 'marka', id: uuidv4() },
];

export const modelTypes = [
  { title: '1', key: 'model', id: uuidv4() },
  { title: '2', key: 'model', id: uuidv4() },
  { title: '2.1', key: 'model', id: uuidv4() },
  { title: '3', key: 'model', id: uuidv4() },
  { title: '3.1', key: 'model', id: uuidv4() },
  { title: '5', key: 'model', id: uuidv4() },
  { title: '5 (A5000)', key: 'model', id: uuidv4() },
  { title: '5.1', key: 'model', id: uuidv4() },
  { title: '5.1 Plus', key: 'model', id: uuidv4() },
  { title: '6', key: 'model', id: uuidv4() },
  { title: '6.1', key: 'model', id: uuidv4() },
  { title: '7.1', key: 'model', id: uuidv4() },
  { title: '8', key: 'model', id: uuidv4() },
  { title: 'A1K', key: 'model', id: uuidv4() },
  { title: 'A5 Pro', key: 'model', id: uuidv4() },
  { title: 'Blade A612', key: 'model', id: uuidv4() },
  { title: 'C Plus XT1723', key: 'model', id: uuidv4() },
  { title: 'Desire 10 Lifestyle', key: 'model', id: uuidv4() },
  { title: 'Desire 626', key: 'model', id: uuidv4() },
  { title: 'Desire 626n', key: 'model', id: uuidv4() },
  { title: 'Desire 816', key: 'model', id: uuidv4() },
  { title: 'Desire 820', key: 'model', id: uuidv4() },
  { title: 'Desire 825', key: 'model', id: uuidv4() },
  { title: 'Desire 830', key: 'model', id: uuidv4() },
  { title: 'G2', key: 'model', id: uuidv4() },
  { title: 'G3', key: 'model', id: uuidv4() },
  { title: 'G4', key: 'model', id: uuidv4() },
  { title: 'G4s', key: 'model', id: uuidv4() },
  { title: 'G5', key: 'model', id: uuidv4() },
  { title: 'G6', key: 'model', id: uuidv4() },
  { title: 'G7 Thinq', key: 'model', id: uuidv4() },
  { title: 'Galaxy A10 (SM-A105)', key: 'model', id: uuidv4() },
  { title: 'Galaxy A20 (SM-A205)', key: 'model', id: uuidv4() },
  { title: 'Galaxy A20e (SM-A202)', key: 'model', id: uuidv4() },
  { title: 'Galaxy A21s (SM-A217F)', key: 'model', id: uuidv4() },
  { title: 'Galaxy A3 (SM-A300)', key: 'model', id: uuidv4() },
  { title: 'Galaxy A3 2016 (SM-A310)', key: 'model', id: uuidv4() },
  { title: 'Galaxy A3 2017 (SM-A320)', key: 'model', id: uuidv4() },
  { title: 'Galaxy A30 (SM-A305)', key: 'model', id: uuidv4() },
  { title: 'Galaxy A30s (SM-A307)', key: 'model', id: uuidv4() },
  { title: 'Galaxy A40 (SM-A405)', key: 'model', id: uuidv4() },
  { title: 'Galaxy A5 2015 (SM-A500)', key: 'model', id: uuidv4() },
  { title: 'Galaxy A5 2016 (SM-A510)', key: 'model', id: uuidv4() },
  { title: 'Galaxy A5 2017 (SM-A520)', key: 'model', id: uuidv4() },
  { title: 'Galaxy A50 (SM-A505)', key: 'model', id: uuidv4() },
  { title: 'Galaxy A51 (SM-A515)', key: 'model', id: uuidv4() },
  { title: 'Galaxy A6 2018 (SM-A600)', key: 'model', id: uuidv4() },
  { title: 'Galaxy A6 Plus (SM-A605)', key: 'model', id: uuidv4() },
  { title: 'Galaxy A6+ (SM-A605)', key: 'model', id: uuidv4() },
  { title: 'Galaxy A7 2017 (SM-A720)', key: 'model', id: uuidv4() },
  { title: 'Galaxy A7 2018 (SM-A750)', key: 'model', id: uuidv4() },
  { title: 'Galaxy A70 (SM-A705)', key: 'model', id: uuidv4() },
  { title: 'Galaxy A71 (SM-A715)', key: 'model', id: uuidv4() },
  { title: 'Galaxy A8 2018 (SM-A530)', key: 'model', id: uuidv4() },
  { title: 'Galaxy A8 Plus 2018 (SM-A730)', key: 'model', id: uuidv4() },
  { title: 'Galaxy A80 (SM-A805)', key: 'model', id: uuidv4() },
  { title: 'Galaxy A9 2018 (SM-A920)', key: 'model', id: uuidv4() },
  { title: 'Galaxy Ace 4', key: 'model', id: uuidv4() },
  { title: 'Galaxy Ace 4 SM-G357', key: 'model', id: uuidv4() },
  { title: 'Galaxy Alpha', key: 'model', id: uuidv4() },
  { title: 'Galaxy J1 2016 (SM-J120)', key: 'model', id: uuidv4() },
  { title: 'Galaxy J3 2016 (SM-J320)', key: 'model', id: uuidv4() },
  { title: 'Galaxy J3 2017 (SM-J330)', key: 'model', id: uuidv4() },
  { title: 'Galaxy J3 2018 (SM-J377)', key: 'model', id: uuidv4() },
  { title: 'Galaxy J4 (SM-J400)', key: 'model', id: uuidv4() },
  { title: 'Galaxy J4 Plus (SM-J415)', key: 'model', id: uuidv4() },
  { title: 'Galaxy J4+ (SM-J415)', key: 'model', id: uuidv4() },
  { title: 'Galaxy J5 2015 (SM-J500)', key: 'model', id: uuidv4() },
  { title: 'Galaxy J5 2016 (SM-J510)', key: 'model', id: uuidv4() },
  { title: 'Galaxy J5 2017 (SM-J530)', key: 'model', id: uuidv4() },
  { title: 'Galaxy J6 2018 (SM-J600)', key: 'model', id: uuidv4() },
  { title: 'Galaxy J6 Plus 2018 (SM-J610)', key: 'model', id: uuidv4() },
  { title: 'Galaxy J6+ 2018 (SM-J610)', key: 'model', id: uuidv4() },
  { title: 'Galaxy J7 2016 (SM-J710)', key: 'model', id: uuidv4() },
  { title: 'Galaxy J7 2017 (SM-J730)', key: 'model', id: uuidv4() },
  { title: 'Galaxy M21', key: 'model', id: uuidv4() },
  { title: 'Galaxy Note 10', key: 'model', id: uuidv4() },
  { title: 'Galaxy Note 10 Lite', key: 'model', id: uuidv4() },
  { title: 'Galaxy Note 10 Lite', key: 'model', id: uuidv4() },
  { title: 'Galaxy Note 10 Plus', key: 'model', id: uuidv4() },
  { title: 'Galaxy Note 10+', key: 'model', id: uuidv4() },
  { title: 'Galaxy Note 2', key: 'model', id: uuidv4() },
  { title: 'Galaxy Note 3', key: 'model', id: uuidv4() },
  { title: 'Galaxy Note 4', key: 'model', id: uuidv4() },
  { title: 'Galaxy Note 5', key: 'model', id: uuidv4() },
  { title: 'Galaxy Note 8 (N950)', key: 'model', id: uuidv4() },
  { title: 'Galaxy Note 9 (N960)', key: 'model', id: uuidv4() },
  { title: 'Galaxy S10', key: 'model', id: uuidv4() },
  { title: 'Galaxy S10 Lite', key: 'model', id: uuidv4() },
  { title: 'Galaxy S10 Plus', key: 'model', id: uuidv4() },
  { title: 'Galaxy S10e', key: 'model', id: uuidv4() },
  { title: 'Galaxy S20', key: 'model', id: uuidv4() },
  { title: 'Galaxy S20 Plus', key: 'model', id: uuidv4() },
  { title: 'Galaxy S20 Ultra', key: 'model', id: uuidv4() },
  { title: 'Galaxy S4', key: 'model', id: uuidv4() },
  { title: 'Galaxy S5', key: 'model', id: uuidv4() },
  { title: 'Galaxy S5 Mini', key: 'model', id: uuidv4() },
  { title: 'Galaxy S5 Neo', key: 'model', id: uuidv4() },
  { title: 'Galaxy S6', key: 'model', id: uuidv4() },
  { title: 'Galaxy S6 Edge', key: 'model', id: uuidv4() },
  { title: 'Galaxy S6 Edge Plus', key: 'model', id: uuidv4() },
  { title: 'Galaxy S7', key: 'model', id: uuidv4() },
  { title: 'Galaxy S7 EDGE', key: 'model', id: uuidv4() },
  { title: 'Galaxy S7 Edge', key: 'model', id: uuidv4() },
  { title: 'Galaxy S8', key: 'model', id: uuidv4() },
  { title: 'Galaxy S8 Plus', key: 'model', id: uuidv4() },
  { title: 'Galaxy S9 (SM-G960)', key: 'model', id: uuidv4() },
  { title: 'Galaxy S9 Plus', key: 'model', id: uuidv4() },
  { title: 'Galaxy Tab S2 (SM-T710)', key: 'model', id: uuidv4() },
  { title: 'Hammer Energy', key: 'model', id: uuidv4() },
  { title: 'Hammer Energy 2', key: 'model', id: uuidv4() },
  { title: 'Honor 10', key: 'model', id: uuidv4() },
  { title: 'Honor 10 Lite', key: 'model', id: uuidv4() },
  { title: 'Honor 10 View', key: 'model', id: uuidv4() },
  { title: 'Honor 20 (YAL-L21)', key: 'model', id: uuidv4() },
  { title: 'Honor 20 Pro', key: 'model', id: uuidv4() },
  { title: 'Honor 5C', key: 'model', id: uuidv4() },
  { title: 'Honor 5X', key: 'model', id: uuidv4() },
  { title: 'Honor 6x', key: 'model', id: uuidv4() },
  { title: 'Honor 7 Lite', key: 'model', id: uuidv4() },
  { title: 'Honor 7X', key: 'model', id: uuidv4() },
  { title: 'Honor 8', key: 'model', id: uuidv4() },
  { title: 'Honor 8X', key: 'model', id: uuidv4() },
  { title: 'Honor 9', key: 'model', id: uuidv4() },
  { title: 'Honor 9 Lite', key: 'model', id: uuidv4() },
  { title: 'iMac', key: 'model', id: uuidv4() },
  { title: 'iPad 2', key: 'model', id: uuidv4() },
  { title: 'iPad 3', key: 'model', id: uuidv4() },
  { title: 'iPad 4', key: 'model', id: uuidv4() },
  { title: 'iPad 6 (A1893)', key: 'model', id: uuidv4() },
  { title: 'iPad Air 1', key: 'model', id: uuidv4() },
  { title: 'iPad Air 2', key: 'model', id: uuidv4() },
  { title: 'iPhone 11', key: 'model', id: uuidv4() },
  { title: 'iPhone 11 Pro', key: 'model', id: uuidv4() },
  { title: 'iPhone 11 Pro Max', key: 'model', id: uuidv4() },
  { title: 'iPhone 5', key: 'model', id: uuidv4() },
  { title: 'iPhone 5S', key: 'model', id: uuidv4() },
  { title: 'iPhone 6', key: 'model', id: uuidv4() },
  { title: 'iPhone 6 Plus', key: 'model', id: uuidv4() },
  { title: 'iPhone 6S', key: 'model', id: uuidv4() },
  { title: 'iPhone 6S Plus', key: 'model', id: uuidv4() },
  { title: 'iPhone 7', key: 'model', id: uuidv4() },
  { title: 'iPhone 7 Plus', key: 'model', id: uuidv4() },
  { title: 'iPhone 8', key: 'model', id: uuidv4() },
  { title: 'iPhone 8 Plus', key: 'model', id: uuidv4() },
  { title: 'iPhone X', key: 'model', id: uuidv4() },
  { title: 'iPhone XR', key: 'model', id: uuidv4() },
  { title: 'iPhone XS', key: 'model', id: uuidv4() },
  { title: 'iPhone XS Max', key: 'model', id: uuidv4() },
  { title: 'iPohne SE', key: 'model', id: uuidv4() },
  { title: 'K10', key: 'model', id: uuidv4() },
  { title: 'K10 2017', key: 'model', id: uuidv4() },
  { title: 'K10 2018', key: 'model', id: uuidv4() },
  { title: 'K11', key: 'model', id: uuidv4() },
  { title: 'K4', key: 'model', id: uuidv4() },
  { title: 'K4 2017', key: 'model', id: uuidv4() },
  { title: 'K40', key: 'model', id: uuidv4() },
  { title: 'K50', key: 'model', id: uuidv4() },
  { title: 'K8', key: 'model', id: uuidv4() },
  { title: 'K8 2017', key: 'model', id: uuidv4() },
  { title: 'K8 2018', key: 'model', id: uuidv4() },
  { title: 'K9', key: 'model', id: uuidv4() },
  { title: 'Lumia 720', key: 'model', id: uuidv4() },
  { title: 'Lumia 730/735', key: 'model', id: uuidv4() },
  { title: 'Lumia 920', key: 'model', id: uuidv4() },
  { title: 'Lumia 930', key: 'model', id: uuidv4() },
  { title: 'Lumia 950', key: 'model', id: uuidv4() },
  {
    title: 'MacBook Pro Retina Mid-2012 A1398 15,4"',
    key: 'model',
    id: uuidv4(),
  },
  { title: 'Mate 10', key: 'model', id: uuidv4() },
  { title: 'Mate 10 Lite', key: 'model', id: uuidv4() },
  { title: 'Mate 10 Pro', key: 'model', id: uuidv4() },
  { title: 'Mate 20', key: 'model', id: uuidv4() },
  { title: 'Mate 20 Lite', key: 'model', id: uuidv4() },
  { title: 'Mate 20 Pro', key: 'model', id: uuidv4() },
  { title: 'Mate 7', key: 'model', id: uuidv4() },
  { title: 'Mate 8', key: 'model', id: uuidv4() },
  { title: 'Mate 9', key: 'model', id: uuidv4() },
  { title: 'Mediapad M5 10', key: 'model', id: uuidv4() },
  { title: 'Mediapad M6 10,8', key: 'model', id: uuidv4() },
  { title: 'MediaPad T1-701W', key: 'model', id: uuidv4() },
  { title: 'Mediapad T3 10', key: 'model', id: uuidv4() },
  { title: 'Mediapad T5', key: 'model', id: uuidv4() },
  { title: 'MI 3/4/4C', key: 'model', id: uuidv4() },
  { title: 'MI 5', key: 'model', id: uuidv4() },
  { title: 'MI 5S', key: 'model', id: uuidv4() },
  { title: 'MI 6', key: 'model', id: uuidv4() },
  { title: 'MI 8', key: 'model', id: uuidv4() },
  { title: 'MI 8 Lite', key: 'model', id: uuidv4() },
  { title: 'Mi 9', key: 'model', id: uuidv4() },
  { title: 'Mi 9', key: 'model', id: uuidv4() },
  { title: 'Mi 9 Lite', key: 'model', id: uuidv4() },
  { title: 'Mi 9 SE', key: 'model', id: uuidv4() },
  { title: 'Mi 9T', key: 'model', id: uuidv4() },
  { title: 'Mi 9T Pro', key: 'model', id: uuidv4() },
  { title: 'Mi 9T Pro', key: 'model', id: uuidv4() },
  { title: 'Mi A1', key: 'model', id: uuidv4() },
  { title: 'MI A2', key: 'model', id: uuidv4() },
  { title: 'MI A2 Lite', key: 'model', id: uuidv4() },
  { title: 'MI A3', key: 'model', id: uuidv4() },
  { title: 'Mi Max', key: 'model', id: uuidv4() },
  { title: 'Mi Max 2', key: 'model', id: uuidv4() },
  { title: 'Mi Max 3', key: 'model', id: uuidv4() },
  { title: 'Mi Mix', key: 'model', id: uuidv4() },
  { title: 'Mi Mix 2', key: 'model', id: uuidv4() },
  { title: 'Mi Mix 2s', key: 'model', id: uuidv4() },
  { title: 'Mi Mix 3', key: 'model', id: uuidv4() },
  { title: 'Mi Note 10', key: 'model', id: uuidv4() },
  { title: 'Moto E4', key: 'model', id: uuidv4() },
  { title: 'Moto G6', key: 'model', id: uuidv4() },
  { title: 'Moto G7 Play (XT1952)', key: 'model', id: uuidv4() },
  { title: 'Moto G8 Plus', key: 'model', id: uuidv4() },
  { title: 'Moto One XT1941', key: 'model', id: uuidv4() },
  { title: 'Office Professional 2019', key: 'model', id: uuidv4() },
  { title: 'One A9S', key: 'model', id: uuidv4() },
  { title: 'One Action', key: 'model', id: uuidv4() },
  { title: 'One M10', key: 'model', id: uuidv4() },
  { title: 'One M8', key: 'model', id: uuidv4() },
  { title: 'One M8S', key: 'model', id: uuidv4() },
  { title: 'One M9', key: 'model', id: uuidv4() },
  { title: 'One Vision', key: 'model', id: uuidv4() },
  { title: 'P Smart 2018', key: 'model', id: uuidv4() },
  { title: 'P Smart 2019', key: 'model', id: uuidv4() },
  { title: 'P Smart Plus', key: 'model', id: uuidv4() },
  { title: 'P Smart Pro', key: 'model', id: uuidv4() },
  { title: 'P Smart Z', key: 'model', id: uuidv4() },
  { title: 'P10', key: 'model', id: uuidv4() },
  { title: 'P10 Lite', key: 'model', id: uuidv4() },
  { title: 'P10 Plus (VKY-L09)', key: 'model', id: uuidv4() },
  { title: 'P10 Pro', key: 'model', id: uuidv4() },
  { title: 'P2', key: 'model', id: uuidv4() },
  { title: 'P20', key: 'model', id: uuidv4() },
  { title: 'P20 Lite', key: 'model', id: uuidv4() },
  { title: 'P20 Pro', key: 'model', id: uuidv4() },
  { title: 'P30', key: 'model', id: uuidv4() },
  { title: 'P30 Lite', key: 'model', id: uuidv4() },
  { title: 'P30 Pro', key: 'model', id: uuidv4() },
  { title: 'P40 Lite', key: 'model', id: uuidv4() },
  { title: 'P40 Lite E', key: 'model', id: uuidv4() },
  { title: 'P8', key: 'model', id: uuidv4() },
  { title: 'P8 Lite', key: 'model', id: uuidv4() },
  { title: 'P8 Lite 2017', key: 'model', id: uuidv4() },
  { title: 'P9', key: 'model', id: uuidv4() },
  { title: 'P9 Lite', key: 'model', id: uuidv4() },
  { title: 'P9 Lite 2017', key: 'model', id: uuidv4() },
  { title: 'P9 Lite Mini 2017', key: 'model', id: uuidv4() },
  { title: 'Pixel 2 XL', key: 'model', id: uuidv4() },
  { title: 'Pocophone F1', key: 'model', id: uuidv4() },
  { title: 'Q6', key: 'model', id: uuidv4() },
  { title: 'Q60', key: 'model', id: uuidv4() },
  { title: 'Redmi 3S', key: 'model', id: uuidv4() },
  { title: 'Redmi 4', key: 'model', id: uuidv4() },
  { title: 'Redmi 4A', key: 'model', id: uuidv4() },
  { title: 'Redmi 4X', key: 'model', id: uuidv4() },
  { title: 'Redmi 5', key: 'model', id: uuidv4() },
  { title: 'Redmi 5 Plus', key: 'model', id: uuidv4() },
  { title: 'Redmi 5A', key: 'model', id: uuidv4() },
  { title: 'Redmi 6/6A', key: 'model', id: uuidv4() },
  { title: 'Redmi 7', key: 'model', id: uuidv4() },
  { title: 'Redmi 7A', key: 'model', id: uuidv4() },
  { title: 'Redmi 8', key: 'model', id: uuidv4() },
  { title: 'Redmi 8A', key: 'model', id: uuidv4() },
  { title: 'Redmi Note 2', key: 'model', id: uuidv4() },
  { title: 'Redmi Note 3 (chiÅ„ska 150mm)', key: 'model', id: uuidv4() },
  { title: 'Redmi Note 3 (EU 152mm)', key: 'model', id: uuidv4() },
  { title: 'Redmi Note 4', key: 'model', id: uuidv4() },
  { title: 'Redmi Note 4X', key: 'model', id: uuidv4() },
  { title: 'Redmi Note 5', key: 'model', id: uuidv4() },
  { title: 'Redmi Note 5 Prime', key: 'model', id: uuidv4() },
  { title: 'Redmi Note 5A', key: 'model', id: uuidv4() },
  { title: 'Redmi Note 6 PRO', key: 'model', id: uuidv4() },
  { title: 'Redmi Note 7', key: 'model', id: uuidv4() },
  { title: 'Redmi Note 8', key: 'model', id: uuidv4() },
  { title: 'Redmi Note 8 Pro', key: 'model', id: uuidv4() },
  { title: 'Redmi Note 8T', key: 'model', id: uuidv4() },
  { title: 'Redmi S2', key: 'model', id: uuidv4() },
  { title: 'S60', key: 'model', id: uuidv4() },
  { title: 'S60', key: 'model', id: uuidv4() },
  { title: 'Tab 3 TB3-850M', key: 'model', id: uuidv4() },
  { title: 'TAB A10', key: 'model', id: uuidv4() },
  { title: 'TAB A8', key: 'model', id: uuidv4() },
  { title: 'Tab E (SM-T560)', key: 'model', id: uuidv4() },
  { title: 'TAB S5', key: 'model', id: uuidv4() },
  { title: 'TAB S6', key: 'model', id: uuidv4() },
  { title: 'U Play', key: 'model', id: uuidv4() },
  { title: 'U Play', key: 'model', id: uuidv4() },
  { title: 'U Ultra', key: 'model', id: uuidv4() },
  { title: 'U11', key: 'model', id: uuidv4() },
  { title: 'U11 Life', key: 'model', id: uuidv4() },
  { title: 'V30', key: 'model', id: uuidv4() },
  { title: 'Watch S1', key: 'model', id: uuidv4() },
  { title: 'Watch S2', key: 'model', id: uuidv4() },
  { title: 'Watch S3', key: 'model', id: uuidv4() },
  { title: 'Watch S4', key: 'model', id: uuidv4() },
  { title: 'X Force', key: 'model', id: uuidv4() },
  { title: 'Xcover 3 (G388)', key: 'model', id: uuidv4() },
  { title: 'Xcover 4 (G390)', key: 'model', id: uuidv4() },
  { title: 'Xcover 4S', key: 'model', id: uuidv4() },
  { title: 'Xperia E5', key: 'model', id: uuidv4() },
  { title: 'Xperia L1', key: 'model', id: uuidv4() },
  { title: 'Xperia M4 AQUA', key: 'model', id: uuidv4() },
];
