// <auto-generated />
using System;
using CommandApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CommandApi.Migrations
{
    [DbContext(typeof(masterContext))]
    partial class masterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Polish_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CommandApi.Models.Zlecenie", b =>
                {
                    b.Property<short>("Rma")
                        .HasColumnType("smallint")
                        .HasColumnName("RMA");

                    b.Property<DateTime?>("DataPrzyjecia")
                        .HasColumnType("date")
                        .HasColumnName("data_przyjecia");

                    b.Property<string>("Imie")
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .HasColumnName("imie")
                        .IsFixedLength(true);

                    b.Property<string>("Informacje")
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("informacje")
                        .IsFixedLength(true);

                    b.Property<decimal?>("KosztCzesci")
                        .HasColumnType("money")
                        .HasColumnName("koszt_czesci");

                    b.Property<decimal?>("KosztNaprawy")
                        .HasColumnType("money")
                        .HasColumnName("koszt_naprawy");

                    b.Property<string>("Marka")
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .HasColumnName("marka")
                        .IsFixedLength(true);

                    b.Property<string>("Model")
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .HasColumnName("model")
                        .IsFixedLength(true);

                    b.Property<string>("Nazwisko")
                        .HasMaxLength(30)
                        .HasColumnType("nchar(30)")
                        .HasColumnName("nazwisko")
                        .IsFixedLength(true);

                    b.Property<int?>("NrTel")
                        .HasColumnType("int")
                        .HasColumnName("nr_tel");

                    b.Property<string>("Rodzaj")
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .HasColumnName("rodzaj")
                        .IsFixedLength(true);

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .HasColumnName("status")
                        .IsFixedLength(true);

                    b.Property<string>("Usterka")
                        .HasMaxLength(300)
                        .HasColumnType("nchar(300)")
                        .HasColumnName("usterka")
                        .IsFixedLength(true);

                    b.HasKey("Rma");

                    b.ToTable("zlecenia");
                });
#pragma warning restore 612, 618
        }
    }
}
