export const exampleTicketList = [
  {
    RMA: 1,
    imie: 'lorem',
    nazwisko: 'ipsum',
    nr_tel: 123456789,
    data_przyjecia: '01.07.2021',
    rodzaj: 'telefon',
    marka: 'iPhone',
    model: '5s',
    usterka: 'zepsuta bateria',
    status: 'done',
    koszt_naprawy: 200,
    koszt_czesci: 100,
    informacje: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  },
  {
    RMA: 2,
    imie: 'lorem',
    nazwisko: 'ipsum',
    nr_tel: 123456789,
    data_przyjecia: '01.07.2021',
    rodzaj: 'telefon',
    marka: 'iPhone',
    model: '5s',
    usterka: 'zepsuta bateria',
    status: 'done',
    koszt_naprawy: 200,
    koszt_czesci: 100,
    informacje: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  },
  {
    RMA: 3,
    imie: 'lorem',
    nazwisko: 'ipsum',
    nr_tel: 123456789,
    data_przyjecia: '01.07.2021',
    rodzaj: 'telefon',
    marka: 'iPhone',
    model: '5s',
    usterka: 'zepsuta bateria',
    status: 'done',
    koszt_naprawy: 200,
    koszt_czesci: 100,
    informacje: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  },
  {
    RMA: 4,
    imie: 'lorem',
    nazwisko: 'ipsum',
    nr_tel: 123456789,
    data_przyjecia: '01.07.2021',
    rodzaj: 'telefon',
    marka: 'iPhone',
    model: '5s',
    usterka: 'zepsuta bateria',
    status: 'done',
    koszt_naprawy: 200,
    koszt_czesci: 100,
    informacje: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  },
  {
    RMA: 5,
    imie: 'lorem',
    nazwisko: 'ipsum',
    nr_tel: 123456789,
    data_przyjecia: '01.07.2021',
    rodzaj: 'telefon',
    marka: 'iPhone',
    model: '5s',
    usterka: 'zepsuta bateria',
    status: 'done',
    koszt_naprawy: 200,
    koszt_czesci: 100,
    informacje: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  },
  {
    RMA: 6,
    imie: 'lorem',
    nazwisko: 'ipsum',
    nr_tel: 123456789,
    data_przyjecia: '01.07.2021',
    rodzaj: 'telefon',
    marka: 'iPhone',
    model: '5s',
    usterka: 'zepsuta bateria',
    status: 'done',
    koszt_naprawy: 200,
    koszt_czesci: 100,
    informacje: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  },
  {
    RMA: 7,
    imie: 'lorem',
    nazwisko: 'ipsum',
    nr_tel: 123456789,
    data_przyjecia: '01.07.2021',
    rodzaj: 'telefon',
    marka: 'iPhone',
    model: '5s',
    usterka: 'zepsuta bateria',
    status: 'done',
    koszt_naprawy: 200,
    koszt_czesci: 100,
    informacje: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  },
  {
    RMA: 8,
    imie: 'lorem',
    nazwisko: 'ipsum',
    nr_tel: 123456789,
    data_przyjecia: '01.07.2021',
    rodzaj: 'telefon',
    marka: 'iPhone',
    model: '5s',
    usterka: 'zepsuta bateria',
    status: 'done',
    koszt_naprawy: 200,
    koszt_czesci: 100,
    informacje: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  },
  {
    RMA: 9,
    imie: 'lorem',
    nazwisko: 'ipsum',
    nr_tel: 123456789,
    data_przyjecia: '01.07.2021',
    rodzaj: 'telefon',
    marka: 'iPhone',
    model: '5s',
    usterka: 'zepsuta bateria',
    status: 'done',
    koszt_naprawy: 200,
    koszt_czesci: 100,
    informacje: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  },
  {
    RMA: 10,
    imie: 'lorem',
    nazwisko: 'ipsum',
    nr_tel: 123456789,
    data_przyjecia: '01.07.2021',
    rodzaj: 'telefon',
    marka: 'iPhone',
    model: '5s',
    usterka: 'zepsuta bateria',
    status: 'done',
    koszt_naprawy: 200,
    koszt_czesci: 100,
    informacje: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  },
  {
    RMA: 11,
    imie: 'lorem',
    nazwisko: 'ipsum',
    nr_tel: 123456789,
    data_przyjecia: '01.07.2021',
    rodzaj: 'telefon',
    marka: 'iPhone',
    model: '5s',
    usterka: 'zepsuta bateria',
    status: 'done',
    koszt_naprawy: 200,
    koszt_czesci: 100,
    informacje: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  },
  {
    RMA: 12,
    imie: 'lorem',
    nazwisko: 'ipsum',
    nr_tel: 123456789,
    data_przyjecia: '01.07.2021',
    rodzaj: 'telefon',
    marka: 'iPhone',
    model: '5s',
    usterka: 'zepsuta bateria',
    status: 'done',
    koszt_naprawy: 200,
    koszt_czesci: 100,
    informacje: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  },
  {
    RMA: 13,
    imie: 'lorem',
    nazwisko: 'ipsum',
    nr_tel: 123456789,
    data_przyjecia: '01.07.2021',
    rodzaj: 'telefon',
    marka: 'iPhone',
    model: '5s',
    usterka: 'zepsuta bateria',
    status: 'done',
    koszt_naprawy: 200,
    koszt_czesci: 100,
    informacje: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  },
  {
    RMA: 14,
    imie: 'lorem',
    nazwisko: 'ipsum',
    nr_tel: 123456789,
    data_przyjecia: '01.07.2021',
    rodzaj: 'telefon',
    marka: 'iPhone',
    model: '5s',
    usterka: 'zepsuta bateria',
    status: 'done',
    koszt_naprawy: 200,
    koszt_czesci: 100,
    informacje: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  },
  {
    RMA: 15,
    imie: 'lorem',
    nazwisko: 'ipsum',
    nr_tel: 123456789,
    data_przyjecia: '01.07.2021',
    rodzaj: 'telefon',
    marka: 'iPhone',
    model: '5s',
    usterka: 'zepsuta bateria',
    status: 'done',
    koszt_naprawy: 200,
    koszt_czesci: 100,
    informacje: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  },
  {
    RMA: 16,
    imie: 'lorem',
    nazwisko: 'ipsum',
    nr_tel: 123456789,
    data_przyjecia: '01.07.2021',
    rodzaj: 'telefon',
    marka: 'iPhone',
    model: '5s',
    usterka: 'zepsuta bateria',
    status: 'done',
    koszt_naprawy: 200,
    koszt_czesci: 100,
    informacje: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  },
  {
    RMA: 17,
    imie: 'lorem',
    nazwisko: 'ipsum',
    nr_tel: 123456789,
    data_przyjecia: '01.07.2021',
    rodzaj: 'telefon',
    marka: 'iPhone',
    model: '5s',
    usterka: 'zepsuta bateria',
    status: 'done',
    koszt_naprawy: 200,
    koszt_czesci: 100,
    informacje: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  },
  {
    RMA: 18,
    imie: 'lorem',
    nazwisko: 'ipsum',
    nr_tel: 123456789,
    data_przyjecia: '01.07.2021',
    rodzaj: 'telefon',
    marka: 'iPhone',
    model: '5s',
    usterka: 'zepsuta bateria',
    status: 'done',
    koszt_naprawy: 200,
    koszt_czesci: 100,
    informacje: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  },
  {
    RMA: 19,
    imie: 'lorem',
    nazwisko: 'ipsum',
    nr_tel: 123456789,
    data_przyjecia: '01.07.2021',
    rodzaj: 'telefon',
    marka: 'iPhone',
    model: '5s',
    usterka: 'zepsuta bateria',
    status: 'done',
    koszt_naprawy: 200,
    koszt_czesci: 100,
    informacje: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  },
  {
    RMA: 20,
    imie: 'lorem',
    nazwisko: 'ipsum',
    nr_tel: 123456789,
    data_przyjecia: '01.07.2021',
    rodzaj: 'telefon',
    marka: 'iPhone',
    model: '5s',
    usterka: 'zepsuta bateria',
    status: 'done',
    koszt_naprawy: 200,
    koszt_czesci: 100,
    informacje: 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum',
  },
];
