USE [master]
GO
/****** Object:  Database [SM2021]    Script Date: 19.11.2021 13:14:37 ******/
CREATE DATABASE [SM2021]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SM2021', FILENAME = N'/var/opt/mssql/data/SM2021.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SM2021_log', FILENAME = N'/var/opt/mssql/data/SM2021_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [SM2021] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SM2021].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SM2021] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SM2021] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SM2021] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SM2021] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SM2021] SET ARITHABORT OFF 
GO
ALTER DATABASE [SM2021] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SM2021] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SM2021] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SM2021] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SM2021] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SM2021] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SM2021] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SM2021] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SM2021] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SM2021] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SM2021] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SM2021] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SM2021] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SM2021] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SM2021] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SM2021] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SM2021] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SM2021] SET RECOVERY FULL 
GO
ALTER DATABASE [SM2021] SET  MULTI_USER 
GO
ALTER DATABASE [SM2021] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SM2021] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SM2021] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SM2021] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SM2021] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SM2021] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [SM2021] SET QUERY_STORE = OFF
GO
USE [SM2021]
GO
/****** Object:  Table [dbo].[clients]    Script Date: 19.11.2021 13:14:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[clients](
	[idClient] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](255) NOT NULL,
	[surname] [nvarchar](255) NOT NULL,
	[phoneNumber] [nvarchar](20) NOT NULL,
	[companyName] [nvarchar](255) NULL,
	[NIP] [nvarchar](20) NULL,
	[email] [nvarchar](255) NULL,
 CONSTRAINT [PK_clients] PRIMARY KEY CLUSTERED 
(
	[idClient] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[devices]    Script Date: 19.11.2021 13:14:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[devices](
	[idDevice] [int] IDENTITY(1,1) NOT NULL,
	[type] [nvarchar](50) NOT NULL,
	[brand] [nvarchar](50) NOT NULL,
	[model] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_devices] PRIMARY KEY CLUSTERED 
(
	[idDevice] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[tickets]    Script Date: 19.11.2021 13:14:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tickets](
	[RMA] [int] IDENTITY(1,1) NOT NULL,
	[idClient] [int] NOT NULL,
	[idDevice] [int] NOT NULL,
	[beginDate] [datetime] NOT NULL,
	[glitch] [nvarchar](255) NOT NULL,
	[repairCost] [money] NULL,
	[partsCost] [money] NULL,
	[endDate] [datetime] NULL,
	[status] [nvarchar](255) NULL,
	[information] [nvarchar](255) NULL,
	[idCompany] [int] NULL,
 CONSTRAINT [PK_tickets] PRIMARY KEY CLUSTERED 
(
	[RMA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[users]    Script Date: 19.11.2021 13:14:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[employees](
	[idEmployee] [int] IDENTITY(1,1) NOT NULL,
	[idCompany] [int] NULL,
	[type] [smallint] NOT NULL,
	[login] [nvarchar](255) NOT NULL,
	[password] [nvarchar](255) NOT NULL,
	[phoneNumber] [nvarchar](20) NOT NULL,
	[name] [nvarchar](50)  NOT NULL,
	[surname] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_employees] PRIMARY KEY CLUSTERED 
(
	[idEmployee] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_users] UNIQUE NONCLUSTERED 
(
	[idCompany] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tickets] ADD  DEFAULT (getdate()) FOR [beginDate]
GO
ALTER TABLE [dbo].[tickets]  WITH CHECK ADD  CONSTRAINT [FK_tickets_eployees] FOREIGN KEY([idCompany])
REFERENCES [dbo].[employees] ([idCompany])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[tickets] CHECK CONSTRAINT [FK_tickets_eployees]
GO
ALTER TABLE [dbo].[tickets]  WITH CHECK ADD  CONSTRAINT [FK_tickets_clients] FOREIGN KEY([idClient])
REFERENCES [dbo].[clients] ([idClient])
GO
ALTER TABLE [dbo].[tickets] CHECK CONSTRAINT [FK_tickets_clients]
GO
ALTER TABLE [dbo].[tickets]  WITH CHECK ADD  CONSTRAINT [FK_tickets_devices] FOREIGN KEY([idDevice])
REFERENCES [dbo].[devices] ([idDevice])
GO
ALTER TABLE [dbo].[tickets] CHECK CONSTRAINT [FK_tickets_devices]
GO
USE [master]
GO
ALTER DATABASE [SM2021] SET  READ_WRITE 
GO
